spring:
 application:
  name: social-media
datasource:
 url: jdbc:postgresql://localhost:5432/social_media
 username: ${DB_USERNAME}
 password: ${DB_PASSWORD}
 driver-class-name: org.postgresql.Driver
jpa:
hibernate:
 dialect: org.hibernate.dialect.PostgreSQLDialect
 ddl-auto: update
 show-sql: true
properties:
 format_sql: true






